name: "bluebell"
mode: "dev"
port: 8081
version: "v.1.0"
start_time: "2023-08-31"
machine_id: 1
log:
  level: "debug"
  filename: "bluebell.log"
  max_size: 200
  max_age: 30
  max_backups: 7

auth:
  jwt_expire: 8760
  
mysql:
  host: "127.0.0.1"
  port: 3306
  username: "root"
  password: "123456"
  dbname: "bluebell"
  max_open_conns: 200
  max_idle_conns: 50

redis:
  host: "8.130.66.151"
  port: 9000
  password: ""
  db: 0
  pool_size: 100
  