version: '1.0'
services:
  mysql:
    image: "mysql:5.7"
    ports:
      - "16161:3306"
    command: "--default-authentication-plugin=mysql_native_password --init-file /data/application/init.go"
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "bluebell"
      MYSQL_PASSWORD: "123456"
    volumes:
      - ./init.sql:/data/application/init.sql
  redis01:
    image: "redis:6.2.6"
    ports:
      - "9000:6379"
  bluebell:
    build: .
    command: sh -c "./wait-for.sh mysql:3306 redis01:6479 -- ./bluebell ./conf/config.yaml"
    depends_on:
      - mysql
      - redis01
    ports:
      - "8828:8081"